-- SQL queries to populate the comments table with the provided data
-- Note: ID will be auto-generated by the database

INSERT INTO "comment" (author, text, date, likes, image) VALUES
('Joe', 'As a solo dev who''s taken up freelancing, Firebase and Supabase both work very well for the kinds of projects I do for clients. There''s really nothing they can''t do since they don''t stop you from combining them with other solutions, and there''s no reason to take on the extra headache of doing everything from scratch if you''re working solo. Firebase is just GCP with an abstraction layer on top - there''s nothing stopping you from spinning up a Node service using Cloud Run for long-running tasks that can''t be deployed as cloud functions, for example. Same goes for Supabase, nothing stopping you from using AWS or other cloud services to supplement what you get for free with it.', '2015-09-01T12:00:00Z', 101, 'https://yt3.googleusercontent.com/GsP5Yvc5jOSop4SJf_75wdOYaEbO-7ZyYhnARodAGRnEMh-OQjGPGzUz2ZtzsHPtqFyHGvmbEtI=s900-c-k-c0x00ffffff-no-rj'),

('Jane', 'I''m pretty used to node+express and doing all the backend work by myself. Baas solutions are cool, unless you need mountains of custom logic. Then they will only slow you down. Coding your own backend and deploying it securely takes experience, but you''ll never have that experience if you never try (;', '2015-09-01T12:05:00Z', 56, 'https://miro.medium.com/v2/resize:fit:2000/1*HkM78Z1G5UKqQNCHwBHRfA.png'),

('Smith', 'C#', '2015-09-01T12:10:00Z', 66, NULL),

('Marry', 'Node/express or Rust/Axum.', '2015-09-01T12:15:00Z', 14, NULL),

('Peter', '. NET Core Web API / SQL Server. I was born by .NET and I''ll die by it. Tools like NSwag and umijs-openapi plugin read the automatically generated Swagger UI from the API and generate typescript types and API fetch functions. Off the beaten path but works for me. All that being said supabase is pretty dope', '2015-09-01T12:20:00Z', 38, 'https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger/_static/custom-info-nswag.png?view=aspnetcore-7.0'),

('John', 'If it''s going to be complicated, NestJs. If not, just Next/Remix with Supabase.', '2015-09-01T12:25:00Z', 14, NULL),

('Lily', 'Ruby on Railsss', '2015-09-01T12:15:00Z', 14, NULL),

('Tom', 'I''m a big fan of Hasura. It''s a GraphQL engine that sits on top of Postgres. It''s open source and you can run it yourself, but they also have a hosted version. It''s really easy to get started with and you can do a lot with it. I''ve used it for a few projects and it''s been great.', '2015-09-01T12:30:00Z', 54, 'https://avatars.githubusercontent.com/u/13966722?s=200&v=4'),

('Jack', 'Laravel is my go to. Extremely stable and robust release cycles, has been around for over 10 years now and it''s all refinement at this stage. It has almost everything baked in (auth, jobs, queues, commands, sessions, etc) and lots of first party modules (like payments).', '2015-09-01T12:35:00Z', 25, 'https://laravel.com/img/logomark.min.svg'),

('Rose', 'I love Ruby on Rails, and since discovering Inertia.js I can''t imagine using anything else for the backend. ActiveRecord is so powerful, and Ruby is so expressive and fun to write in. I used to start projects with RoR and try to incorporate React with APIs or GraphQL, but would get tired of the context change. With Inertia, React is just the view layer in the monolith, it doesn''t feel separate at all. I love working in this stack and will probably start all future projects heavier than a brochure page with it. If anybody uses React or Laravel, do yourself a favor and check out Inertia, it brings the whole stack together.', '2015-09-01T12:40:00Z', 18, 'https://avatars.githubusercontent.com/u/5429470?s=200&v=4'),

('David', 'Golang. I use that for work on the daily so it''s what''s easiest for me.', '2015-09-01T12:45:00Z', 10, 'https://www.freecodecamp.org/news/content/images/2021/10/golang.png'),

('Linda', 'Since you are going solo, saving time on setup/infra/devops make sense (and focus time on dev). For custom logic, Supabase actually let you write edge custom functions using Deno. It should cover a vast amount of requirements for having a custom backend.', '2015-09-01T12:50:00Z', 9, NULL),

('Mike', 'I used to use nextjs with supabase, but recently switched to nextjs with planetscale and clerky. both hosted on vercel. nothing against supabase btw, both stacks are great, just trying the https://create.t3.gg/ stack to learn some new things.', '2015-09-01T12:55:00Z', 31, NULL),

('Emily', 'Depends. I like to use a Python framework for ML-based projects (Django or FastAPI). For the easiest stack, I generally use Next/Supabase', '2015-09-01T13:00:00Z', 8, NULL),

('Bob', 'I''ve been using NestJs for the backend of a sass I''ve been building. I don''t think I''ll use it again on my next project. I''ve been itching to learn something else outside the JS ecosystem like Rails or Phoenix. Supabase looks cool too though for a solo dev.', '2015-09-01T13:05:00Z', 7, NULL),

('Sara', 'Sometimes .Net, sometimes Express, sometimes Next. Next can be good esp for smaller teams or solo devs since you can do backend/frontend all on server side, but it is fairly opinionated and has its own quirks.', '2015-09-01T13:10:00Z', 6, 'https://cdn.sanity.io/images/3do82whm/next/4b1f008289a88f4438a1c983fb32cf1a636d9d0e-1000x667.png?w=720&h=480&fit=clip&auto=format');